Algoritmo "Atividade 1"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Thomaz Koga
// Data atual  : 29/04/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     nota<- 100
     escreva ("Resultado:", nota)

Fimalgoritmo