Algoritmo "Atividade 2 - variáveis"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Thomaz Koga
// Data atual  : 29/04/2020
Var
// Seção de Declarações das variáveis 
      nota: inteiro, nota2: real, nome: caractere, passou: logico;
      

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo